[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
bincode = "1.3"